### ISSUE TITLE
답을 제출한 문항으로 돌아가면 제출값이 저장되어 있지 않은 문제 

### ISSUE THREAD

**Issue by nuatmochoi** [viaSSH/exam-boom#6]
문제 제출 이후에 풀었던 문제로 돌아가면 라디오 버튼은 선택한 항목이 눌러져 있는데, 
그상태에서 바로 `저장 후 계속` 버튼을 누르면 `값을 선택해주세요` Alert 창이 뜹니다. 값이 저장되어 있지 않은 것 같아요

P.S. Alert 창이 뜬 이후에, 다음 문제로 넘어가긴 하네요.

**Comment by viaSSH** [comment]
state의 selectedAnswer 배열 변수의 길이로 답안선택 여부를 체크하였는데, 다른문제로 이동했다 돌아올 경우 해당 배열 변수가 초기화가 되서 나타난 에러네요.
기존 문제로 돌아올때 해당 변수도 값을 채워줘야겠네요!!
