### ISSUE TITLE
랜덤문제 선택 시 문제가 나타나지 않는 버그

### ISSUE THREAD

**Issue by viaSSH** [viaSSH/exam-boom#7]
@boomkim
코드 수정을 하다가 뭔가가 충돌이 난건지.... Merge conflict가 난건지 랜덤문제 기능이 안되네요

https://exam.viassh.com/exam/adp/random/1

위 처럼 URL이 /adp/ 뒤로 랜덤이 들어가서 문제 번호가 숫자가 아니라 "random" 이라는 문자열로 들어가 오류가 뜨고있는데, 이전에는 어떻게 해결하셨었나요??

그 부분을 특별히 건든건 없는데 급 버그가 생겼네요

**Comment by boomkim** [comment]
random 이 아니라 /app/index.js 부분이 수정되면서 생긴 문제로 보이네요. 거기에서 라우팅을 잡아줬었는데 새로 누군가 커밋하면서 예전버전을 그대로 사용하셨나보네요...

**Comment by viaSSH** [comment]
흠... 오늘 있었던 Github 오류랑 연관이 있을까요....ㅋㅋㅋㅋ 아니면 단순 Merge 할때 휴먼에러인지.
아무튼 /app/index.js에 한줄 추가로 오류 수정했습니다.
